#%RAML 0.8
title: supermarket-order-manage-api
mediaType: application/json

/products:
  get:
    description: As a customer I can get all the products then I can get products to buy
    responses:
      200:
        body:
          application/json:


  post:
    description: As an admin I can create a production so that customer can buy the production
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
              "price": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "categoryId": {
                "type": "integer"
               }
            },
            "required": ["price", "name", "categoryId"]
          }
        example: |
          {
            "price": 10,
            "name": "apple",
            "categoryId": 2
          }
    responses:
      201:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "itemUri": {
                    "type": "string"
                  }
                },
                "required": ["itemUri"]
              }
            example: |
              {
                "itemUri": "products/10"
              }

  /{id}:
    get:
      description: As a customer I can view the production detail so that I can decide whether to buy the production or not.
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "object",
                  "required": true,
                  "properties": {
                    "price": {
                      "type": "number"
                    },
                    "name": {
                      "type": "string"
                    },
                    "categoryUri": {
                      "type": "string"
                    },
                    "id": {
                      "type": "integer"
                    },
                    "categoryId": {
                      "type": "integer"
                     }
                  },
                  "required": ["price", "name", "categoryUri", "id", "categoryId"]
                }
              example: |
                {
                  "price": 10,
                  "categoryUri": "categories/2",
                  "name": "apple",
                  "id": 1,
                  "categoryId": 2
                }

    delete:
      description: As a admin I can delete a production so that customer won't see outdated production
      responses:
        204:

    put:
      description: As a admin I can update a production so that customer can see the newer production details
      body:
        application/json:
          schema: |
            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "required": true,
              "properties": {
                "price": {
                  "type": "number"
                },
                "name": {
                  "type": "string"
                },
                "categoryId": {
                  "type": "integer"
                 }
              },
              "required": ["price", "name", "categoryUri", "id", "categoryId"]
            }
          example: |
            {
              "price": 10,
              "name": "apple",
              "categoryId": 2
            }
      responses:
        204:

/orders:
  get:
    description: As a admin, I can get all orders so that I can manage them.
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "totalCount": {
                  "type": "integer"
                },
                "orders": {
                  "type": "array",
                  "properties": {
                    "provider_id": {
                      "type": "integer"
                    },
                    "product_id": {
                      "type": "integer"
                    },
                    "count": {
                      "type": "integer"
                     }
                  },
                  "required": ["product_id", "provider_id", "count"]
                }
              }
            example: |
              {
                "totalCount": 1,
                [{
                  "provider_id": 1,
                  "product_id": 2,
                  "count": 10000
                }]

              }

  post:
    description: As a admin, I can create an order so that I can buy some products from provider.
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
              "provider_id": {
                "type": "integer"
              },
              "product_id": {
                "type": "integer"
              },
              "count": {
                "type": "integer"
               }
            },
           "required": ["product_id", "provider_id", "count"]
          }
        example: |
          {
            "provider_id": 1,
            "product_id": 2,
            "count": 10000
          }
    responses:
      201:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "order_url": {
                    "type": "string",
                    "required": true
                  }
                }
              }
            example: |
              {
                "order_id": "orders/10"
              }

 /{id}:
    get:
      description: As a admin, I can get an order so that I can manage it.
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "array",
                  "properties": {
                    "provider_id": {
                      "type": "integer"
                    },
                    "product_id": {
                      "type": "integer"
                    },
                    "count": {
                      "type": "integer"
                     }
                  },
                  "required": ["product_id", "provider_id", "count"]
                }
              example: |
                {
                  "provider_id": 1,
                  "product_id": 2,
                  "count": 10000
                }

    put:
      description: As a admin, I can update an order so that I modify order details.
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "provider_id": {
                    "type": "integer"
                  },
                  "product_id": {
                    "type": "integer"
                  },
                  "count": {
                    "type": "integer"
                   }
                },
               "required": ["product_id", "provider_id", "count"]
              }
            example: |
              {
                "provider_id": 1,
                "product_id": 2,
                "count": 10000
              }
        responses:
          204:


    delete:
      description: As a admin, I can delete an order so that I can remove an useless order.
        204:

/providers:
  get:
    description: As a admin, I can get all providers so that I can manage them.
    responses:
      200:
        body:
          application/json:
           schema: |
             {
               "$schema": "http://json-schema.org/draft-04/schema#",
               "type": "object",
               "totalCount": {
                 "type": "integer"
               },
               "providers": {
                 "type": "array",
                 "properties": {
                   "id": {
                     "type": "integer"
                   },
                   "name": {
                     "type": "string"
                    }
                 },
                 "required": ["id", "name"]
               }
             }
          example: |
            {
              "totalCount": 2,
              [{
                "id": 1,
                "name": "Super Apple"
               }, {
                "id": 2,
                "name": "Little cookie"
              }]
            }


  post:
    description: As a admin, I can create a provider so that I can buy products from a new provider.
    body:
      application/json:
        schema: |
           {
             "$schema": "http://json-schema.org/draft-04/schema#",
             "type": "object",
             "properties": {
               "name": {
                "type": "string",
                "required": true
               }
             }
           }
        example: |
          {
            "name": "Little Yellow Duck"
          }

    responses:
        201:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "object",
                  "properties": {
                    "provider_url": {
                      "type": "string",
                      "required": true
                    }
                  }
                }
              example: |
                {
                  "provider_id": "providers/3"
                }

  /{id}:
    get:
      description: As a admin, I can get an provider so that I can view its details.
      responses:
        200:
          body:
            application/json:
             schema: |
               {
                 "$schema": "http://json-schema.org/draft-04/schema#",
                 "type": "object",
                 "properties": {
                   "id": {
                     "type": "integer"
                   },
                   "name": {
                     "type": "string"
                    }
                 },
                  "required": ["id", "name"]
               }
            example: |
              {
                "id": 1,
                "name": "Super Apple"
              }

    put:
      description: As a admin, I can update a provider's detail when this provider's detail had changed.
      body:
        application/json:
          schema: |
           {
             "$schema": "http://json-schema.org/draft-04/schema#",
             "type": "object",
             "properties": {
               "id": {
                "type": "string",
                "required": true
               },
               "name": {
                "type": "string",
                "required": true
               }
             }
           }
          example: |
            {
              "id": 1,
              "name": "Little Yellow Duck"
            }
      responses:
        204:


    delete:
      description: As a admin, I can delete a provider when I won't to buy products from it.
        204:

