#%RAML 1.0
title: supermarket-api
version: 1.0
baseUri: /
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/:
  get:
    description: 测试根路径
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "items": "/items"
              }

/items:
  get:
    description: 获取所有的商品列表
    responses:
      200:
        body:
          application/json:
            properties:
              totalCount: integer
              items:
                properties:
                  []:
                    properties:
                      price: integer
                      categoryUri: string
                      name: string
                      id: integer
                      categoryId: integer
  post:
    description: 插入一个商品信息
    body:
      application/json:
        properties:
          name: string
          price: number # double
          categoryId: integer
    responses:
      201:
        body:
          application/json:
            properties:
               itemUri: string

  /{id}:
    get:
      description: 根据商品id获取指定商品信息
      responses:
        200:
          body:
            application/json:
              properties:
                price: integer
                categoryUri: string
                name: string
                id: integer
                categoryId: integer

    delete:
      description: 删除指定商品id的商品信息
      responses:
        204:

    put:
      description: 更新指定商品id的商品信息
      body:
        application/json:
          properties:
            price: number #double
            name: string
            categoryId: integer
      responses:
        204:

/categories:
  get:
    description: 获取所有的分类列表
    responses:
      200:
        body:
          application/json:
            properties:
              totalCount: integer
              categories:
                properties:
                  []:
                    properties:
                      name: string
                      id: integer
                      categoryUri: string
  post:
    description: 插入一个分类信息
    body:
      application/json:
        properties:
          name: string
    responses:
      201:
        body:
          application/json:
            properties:
              categoryUri: string

  /{id}:
    get:
      description: 根据分类id获取指定商品信息
      responses:
        200:
          body:
            application/json:
              properties:
                price: integer
                categoryUri: string
                name: string
                id: integer
                categoryId: integer

    delete:
      description: 删除指定id的分类信息
      responses:
        204:
          description: 删除成功
        412:
          description: 删除失败，该分类下还有商品，不能删除
          body:
            application/json:
              example : |
                {
                  "meaasge": "该分类下还有商品，不能删除！"
                }
    put:
      description: 更新指定id的分类信息
      body:
        application/json:
          properties:
            name: string
      responses:
        204:
/carts:
  get:
    description: 获取所有的购物车列表
    responses:
      200:
        body:
          application/json:
            properties:
              totalCount: integer
              items:
                properties:
                  []:
                    properties:
                      id: integer
                      userId: string
                      items:
                        properties:
                          []:
                            properties:
                              price: integer
                              categoryUri: string
                              name: string
                              id: integer
                              categoryId: integer
  post:
    description: 插入一个购物车信息
    body:
      application/json:
        properties:
          userId: integer
          items: integer[]
    responses:
      201:
        body:
          application/json:
            properties:
              cartUri: string

  /{id}:
    get:
      description: 根据购物车id获取指定购物车详细信息
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                userId: string
                items:
                  properties:
                    []:
                      properties:
                        price: integer
                        categoryUri: string
                        name: string
                        id: integer
                        categoryId: integer

    delete:
      description: 删除指定id的购物车信息
      responses:
        204:

    put:
      description: 更新指定id的购物车信息
      body:
        application/json:
          properties:
            userId: integer
      responses:
        204:

    /items/{id}:
      put:
        description: 更新指定 cart.id 下 items.id 的购物车信息
        body:
          application/json:
            example : |
              {}
        responses:
          204:
